spring:
  datasource:
    url: jdbc:h2:mem:test;mode=MYSQL;DATABASE_TO_UPPER=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations:
      - classpath:sql/user.sql

logging:
  level: 
    com: debug
    org: debug
    cn: debug
